### PR TITLE
229 fix abilities

### LINKED ISSUE #229: Fix ability system
Clean up the current ability system to work better with the database and be more expandable for animations.

### PR DESCRIPTION
**Pull request by ThBrokenToaster**
Fixes #229 .

Changes proposed in this pull request:
- Movement area for each unit is now highlighted
- Abilities highlight the area they will hit
- Abilities system is more modular now and functions under more parameters

### CODE REVIEW

**Review by Toeecko — DISMISSED** [review]

File: Assets/Scripts/Battlefield/AStar/BFS.cs [hunk 1]
```diff
@@ -0,0 +1,233 @@
...
+    //                    {
+    //                        openList.Add(child);
+    //                    }
+    //                }
+    //            }
+    //        }
+        
+    //        return null;
+    //    }
+    //}
```
Comment (wynn-rj) [inline Assets/Scripts/Battlefield/AStar/BFS.cs]: Can this be deleted?

**Review by gdiago — DISMISSED** [review]
Looks good, but as RJ's comment said, try to remove the commented out code if it is not going to be used

File: Assets/Scripts/Battlefield/AStar/BFS.cs (hunk 1 above)
Comment (ThBrokenToaster) [reply Assets/Scripts/Battlefield/AStar/BFS.cs]: yes, forgot it was there

**Review by wynn-rj — APPROVED** [review]

**Review by Toeecko — APPROVED** [review]
