### PR TITLE
103 fix grid holder

### LINKED ISSUE #103: Fix tile container
The battlefield tile container currently doesn't populate properly

### PR DESCRIPTION
**Pull request by ThBrokenToaster**
Fixes #103 .

Changes proposed in this pull request:
- Allows the a star system easy access to the grid array through the character brain

### CODE REVIEW

**Review by Toeecko — DISMISSED** [review]
Opened in Unity, looks good

File: Assets/Scripts/Battlefield/AbstractTurnBrain.cs [hunk 1]
```diff
@@ -11,6 +11,8 @@ namespace SwordAndBored.Battlefield
 {
     public abstract class AbstractTurnBrain : MonoBehaviour
     {
+        public Tile[,] tiles;
```
Comment (subashch6) [inline Assets/Scripts/Battlefield/AbstractTurnBrain.cs]: Don't just hold the Tiles[,] array but instead hold the GridHolder itself.

File: Assets/Scripts/Battlefield/CharacterFactory.cs [hunk 2]
```diff
@@ -66,6 +66,7 @@ void Awake()
                 //brain
                 brain.tileIndictor = indicator;
                 brain.startCoordinates = new Vector2(numUnits, 5);
+                brain.tiles = grid.tiles;
```
Comment (subashch6) [inline Assets/Scripts/Battlefield/CharacterFactory.cs]: instead of holding the TIles[,] array. Take hold of the gridHolder itself since that is a much more robust object than the Tiles array.

File: Assets/Scripts/Battlefield/GridSystem/Tile.cs [hunk 3]
```diff
@@ -7,9 +7,16 @@ public class Tile : MonoBehaviour
...
     public bool walkable = true;
+    [HideInInspector]
+    public Vector2 coordinates;
 
     public Vector3 GetPos()
     {
         return transform.position;
     }
+
+    public Vector2 GetCoordinates()
```
Comment (subashch6) [inline Assets/Scripts/Battlefield/GridSystem/Tile.cs]: I know this is picky but please don't use Coordinates but something more explicit like GridCoordinates() or the like because GetPos() and GetCoordinates() sound like the same thing in the unity context.

**Review by subashch6 — CHANGES_REQUESTED** [review]
Essentially just give the GridHolder itself to the TurnBrain and not just the Tiles[,] that the GridHolder holds and check you PascalCasing and code style and naming in general.

**Review by Toeecko — APPROVED** [review]

**Review by subashch6 — APPROVED** [review]
